title: Here Be Dragons | D&D Streaming Adventures
description: >
  Jared Sartin is the Dungeon Master for this streaming D&D group. The group
  consists of new and veteran players and is set in a whole new world of Nyr.
  Streams happen on Twitch.tv on the 1st and 3rd Saturdays of the month.
social_links:
- url: https://twitch.tv/HereBeDragonsDnD
  image: twitch.png
- url: https://instagram.com/HereBeDragonsDnD
  image: instagram.png
- url: https://discord.gg/9hZQyC5
  image: discord.png
- url: https://www.patreon.com/herebedragonsdnd
  image: patreon.png
- url: https://herebedragonsdnd.bigcartel.com
  image: merch.png
- url: https://twitter.com/HereBDragonsDnD
  image: twitter.png
- url: https://www.facebook.com/HereBeDragonsDnD
  image: facebook.png
- url: https://www.amazon.com/hz/wishlist/ls/1FAAV1D2JC404?ref_=wl_share
  image: amazon.png